[diffusion]
boundary_condition = "Dirichlet"
method             = "euler"

[visualization]
export   = true
interval = 1

[[visualize_agent]]
name                    = "MyCell"
additional_data_members = ["cell_color_"]

# ───────────────────────────────────────────────────────────────────
# <<< ADD THIS BLOCK >>>
[[visualize_diffusion]]
# must exactly match the name you passed to DefineSubstance(...)
name      = "RONS"
# optional prettifiers:
title     = "RONS concentration"
color_map = "Viridis"
# pick some contour levels if you like
levels    = [0.0, 0.25, 0.5, 0.75, 1.0]
# ───────────────────────────────────────────────────────────────────
